### ISSUE TITLE
Emojis in contact names causing errors

### ISSUE THREAD

**Issue by andwati** [s-nikravesh/telegram-json-to-vcf#3]
Hey,🌝
I like your project here, it has helped alot.
So I have some contact names that are saved with an emoji and text.The program throws an error an terminates at that contact name.The previous are written correctly to the vcf file.

![th_1](https://user-images.githubusercontent.com/56686898/98506150-ef813700-226b-11eb-8128-0adc09db9113.JPG)
I have to manually go through the json file to remove them.any automatic fix?

**Comment by s-nikravesh** [comment]
> Hey,full_moon_with_face
> I like your project here, it has helped alot.
> So I have some contact names that are saved with an emoji and text.The program throws an error an terminates at that contact name.The previous are written correctly to the vcf file.
> 
> ![th_1](https://user-images.githubusercontent.com/56686898/98506150-ef813700-226b-11eb-8128-0adc09db9113.JPG)
> I have to manually go through the json file to remove them.any automatic fix?

Hi. I'm glad that it has helped you.
The problem was with the encoding. I fixed it about three weeks ago. Now, it uses UTF-8 encoding, and I think there should be no problems with emojis.
Check out the README file.
