### ISSUE TITLE
utf8 encoding not support!

### ISSUE THREAD

**Issue by MRSheikh** [s-nikravesh/telegram-json-to-vcf#4]
hi.
i have .json file with utf8 characters. when convert it to VCF file utf8 characters is shown as unknown characters.
please help.

**Comment by s-nikravesh** [comment]
> hi.
> i have .json file with utf8 characters. when convert it to VCF file utf8 characters is shown as unknown characters.
> please help.

Hi. The issue with UTF-8 encoding was solved a couple of weeks ago. Take a look at the README.md file.
